### ISSUE TITLE
question: about the watch

### ISSUE THREAD

**Issue by samulefevre** [Atinux/nuxt-deno-kv#1]
Every time you add an entry, it reads all lines again, there is no way to have only the last entry added streamed ?

**Comment by atinux** [comment]
I think that should be possible by improving the key being watched to add more granularity (todo updated, todo deleted, todo added, etc.)

**Comment by samulefevre** [comment]
ok thank you

**Comment by samulefevre** [comment]
I tried to implement the granularity but can't make it works. By changing the way to do it, i was meaning for reducing  database cost by doing less reads, but it becomes more complex.

**Comment by samulefevre** [comment]
i solved it
